app/models.py
class Source:
    '''
    Source class to define Source Objects
    '''

    def __init__(self,id,name,description,url,category,country,language):
        self.id =id
        self.name = name
        self.description = description
        self.url = url
        self.category = category
        self.country = country
        self.language = language      

class Articles():
    '''
    Articles class that defines Article objects
    '''
    def __init__(self,id,author,title,description,url,image,date):
        self.id = id
        self.author = author
        self.title = title
        self.description = description
        self.url = url
        self.image = image
        self.date = date        

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options

bootstrap = Bootstrap()
def create_app (config_name):
    app = Flask(__name__)

    app.config.from_object(config_options[config_name])

    bootstrap.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .request import configure_request
    configure_request(app)

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main',__name__)

from . import views

app/main/views.py
from flask import render_template,request,redirect,url_for
from . import main
from ..request import get_source,get_articles
from ..models import Source,Articles

# Views
@main.route('/')
def index():

    '''
    View root page function that returns the index page and its data i.e news source
    '''
    general = get_source('general')
    science = get_source('science')
    business = get_source('business')
    technology = get_source('technology')
    health = get_source('health')
    entertainment = get_source('entertainment')
    sports = get_source('sports')

    return render_template('index.html',general = general, science = science, business = business,technology = technology, health = health, entertainment = entertainment, sports = sports)


@main.route('/sources/<id>')
def articles(id):
	'''
	view articles page
	'''
	articles = get_articles(id)

	return render_template('articles.html',articles = articles)

app/views.py
from flask import render_template
from app import app
from .request import get_source,get_articles


# Views
@app.route('/')
def index():

    '''
    View root page function that returns the index page and its data i.e news source
    '''
    general = get_source('general')
    science = get_source('science')
    business = get_source('business')
    technology = get_source('technology')
    health = get_source('health')
    entertainment = get_source('entertainment')
    sports = get_source('sports')

    return render_template('index.html',general = general, science = science, business = business,technology = technology, health = health, entertainment = entertainment, sports = sports)


@app.route('/sources/<id>')
def articles(id):
	'''
	view articles page
	'''
	articles = get_articles(id)

	return render_template('articles.html',articles = articles)

app/templates/articles.html
{%extends 'base.html'%}
{% block content%}
<div class="container">
    <h3> Top Headlines</h3>
    {% for article_row in articles_list | batch(4)%}
    <div class="row">
        {% for article in article_row %}
        <div class="col-md-3">
            <div class="thumbnail">
                <a href="/articles/{{article.url}}" target="_blank">
                    <img src="/articles/{{article.image}}" alt="/articles/{{article.title}}" class="img-responsive" styles="height:50px">
                </a>
                <div class="caption">
                    <h4><a href="/articles/{{article.url}}" target="_blank">{{article.title |truncate(40)}}</a></h4>
                    <p>{{article.description | truncate(100)}}</p>
                    <a href="/articles/{{article.url}}" target="_blank">READ THIS ARTICLE</a>
                </div>
                <div class="footer">
                    Published at: {{article.date}}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endfor %}
</div>
{% endblock%}

app/templates/base.html
{% extends 'bootstrap/base.html'%}

{% block styles%}
{{ super() }}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">{%
endblock %}

{% block navbar %}
    {% include 'navbar.html' %}
{%endblock%}    

app/templates/index.html
{%extends 'base.html'%}
{% import 'macros.html' as macro %}

{% block content %}
<div class="container-fluid">
    <!--Top General News Sources  -->
    <h3> Top General News Sources</h3>
    <hr>

    {{ macro.displaySourceList(general)}}

    <!--Top Science Sources  -->
    <h3> Top Science News Sources</h3>
    <hr>

    {{ macro.displaySourceList(science)}}

    <!--top Business News Sources -->
    <h3> Top Business News Sources</h3>
    <hr>

    {{ macro.displaySourceList(business)}}

    <!-- Top Technology News Sources -->
    
    <h3> Top Technology News Sources</h3>
    <hr>

    {{ macro.displaySourceList(technology)}}

    <!-- Top Health News Sources  -->
    <h3> Top Health News Sources</h3>
    <hr>

    {{ macro.displaySourceList(health)}}

    <!-- Top entertainment sources  -->
    
    <h3> Top Entertainment News Sources</h3>
    <hr>

    {{ macro.displaySourceList(entertainment)}}

    <!-- Top sports sources  -->
    
    <h3> Top Sports News Sources</h3>
    <hr>

    {{ macro.displaySourceList(sports)}}

</div>
{%endblock%}

app/templates/macros.html
{% macro displaySourceList(source_list) %}

{% for source_row in source_list |batch(3)%}
<div class="row">
    {% for sources in source_row%}
    <div class="col-md-3">
        <div class="panel">
            <div class="panel-heading">
                <a href="/sources/{{sources.id}}">
                    {{ sources.name}}
                </a>
            </div>
            <div class="panel-body">
                <p>
                    {{ sources.description |truncate(150)}}
                </p>
                <a href="{{url_for('main.articles',id=sources.id)}}" class="btn btn-info btn-sm">Visit {{sources.name}}</a>
            </div>
        </div>
        <br>
    </div>
    {% endfor %}
</div>
{% endfor %}
{% endmacro %}

app/templates/navbar.html
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">NEWS HUB</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="./index.html">SOURCES</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="./articles.html">ARTICLES</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>